version: "3.3"

services:
  spk-video-encoder: # name of the service
    build: .
    image: spk-video-encoder # the image to use
    container_name: spk-video-encoder # what to label the container for docker ps
    restart: always # restart if failed, until we stop it ourselves
    #external_links:
      #- mongo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - ipfs
    networks:
      - spk-video-encoder
    environment:
      IPFS_HOST: ipfs:5001
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - ./data/video-encoder:/root/.spk-encoder
  ipfs:
    container_name: ipfs2
    image: ipfs/kubo:v0.18.1
    command:
      - daemon
      - --enable-pubsub-experiment
    networks:
      - spk-video-encoder
    ports:
      - "4001:4001"
    environment: 
      IPFS_PATH: /etc/ipfs
    volumes:
      - ./data/ipfs-2:/etc/ipfs
      
networks:
  spk-video-encoder:
    driver: bridge
